name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Configure
        run: |
          mkdir -p build
          cmake -DUNIQUE_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE="Release" -B build -S .
        shell: bash

      - name: Build Tests
        run: cmake --build build --target "Unique_Tests" --config "Release"

      - name: Run unit tests
        run: cd build && ctest --build-config "Release" --progress